### ISSUE TITLE
Error when deploying ec2 script - Stable DIfusion Web UI process not starting

### ISSUE THREAD

**Issue by stenio123** [awslabs/stable-diffusion-aws-extension#195]
### Describe the bug

Stable Diffusion Web UI is not launching, getting error

```
Launching Web UI with arguments: --enable-insecure-extension-access --skip-torch-cuda-test --no-half --listen
Traceback (most recent call last):
  File "launch.py", line 48, in <module>
    main()
  File "launch.py", line 44, in main
    start()
  File "/home/ubuntu/stable-diffusion-webui/stable-diffusion-webui/modules/launch_utils.py", line 432, in start
    import webui
  File "/home/ubuntu/stable-diffusion-webui/stable-diffusion-webui/webui.py", line 13, in <module>
    initialize.imports()
  File "/home/ubuntu/stable-diffusion-webui/stable-diffusion-webui/modules/initialize.py", line 21, in imports
    import gradio  # noqa: F401
  File "/home/ubuntu/stable-diffusion-webui/stable-diffusion-webui/venv/lib/python3.8/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/home/ubuntu/stable-diffusion-webui/stable-diffusion-webui/venv/lib/python3.8/site-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/home/ubuntu/stable-diffusion-webui/stable-diffusion-webui/venv/lib/python3.8/site-packages/gradio/components/annotated_image.py", line 12, in <module>
    from gradio import utils
  File "/home/ubuntu/stable-diffusion-webui/stable-diffusion-webui/venv/lib/python3.8/site-packages/gradio/utils.py", line 353, in <module>
    class AsyncRequest:
  File "/home/ubuntu/stable-diffusion-webui/stable-diffusion-webui/venv/lib/python3.8/site-packages/gradio/utils.py", line 372, in AsyncRequest
    client = httpx.AsyncClient()
  File "/home/ubuntu/stable-diffusion-webui/stable-diffusion-webui/venv/lib/python3.8/site-packages/httpx/_client.py", line 1397, in __init__
    self._transport = self._init_transport(
  File "/home/ubuntu/stable-diffusion-webui/stable-diffusion-webui/venv/lib/python3.8/site-packages/httpx/_client.py", line 1445, in _init_transport
    return AsyncHTTPTransport(
  File "/home/ubuntu/stable-diffusion-webui/stable-diffusion-webui/venv/lib/python3.8/site-packages/httpx/_transports/default.py", line 275, in __init__
    self._pool = httpcore.AsyncConnectionPool(
TypeError: __init__() got an unexpected keyword argument 'socket_options'
```

### Expected Behavior

Service starts and is listening to port 7860

### Current Behavior

After running the first CloudFormation to install ec2, server is not live. If I go to the server, and run 
```
lsof -i :7860
```

There is no process is using this port. Checking the service

```
sudo systemctl status sd-webui.service
sd-webui.service - Stable Diffusion UI server
     Loaded: loaded (/etc/systemd/system/sd-webui.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) since Thu 2023-09-14 14:27:59 UTC; 2s ago
    Process: 11871 ExecStart=/home/ubuntu/stable-diffusion-webui/webui.sh --enable-insecure-extension-access --skip-torch-cuda-test --no-half --listen (code=exited, status=0/SUCCESS)
   Main PID: 11871 (code=exited, status=0/SUCCESS)
ubuntu@ip-172-31-19-69:/var/log$ 
``` 
I checked ps aux and the service kept restarting as expected, so I stopped it and ran manually to check

```
sudo systemctl stop sd-webui.service
/home/ubuntu/stable-diffusion-webui/webui.sh --enable-insecure-extension-access --skip-torch-cuda-test --no-half --listen
```
And got error:
```
Launching Web UI with arguments: --enable-insecure-extension-access --skip-torch-cuda-test --no-half --listen
Traceback (most recent call last):
  File "launch.py", line 48, in <module>
    main()
  File "launch.py", line 44, in main
    start()
  File "/home/ubuntu/stable-diffusion-webui/stable-diffusion-webui/modules/launch_utils.py", line 432, in start
    import webui
  File "/home/ubuntu/stable-diffusion-webui/stable-diffusion-webui/webui.py", line 13, in <module>
    initialize.imports()
  File "/home/ubuntu/stable-diffusion-webui/stable-diffusion-webui/modules/initialize.py", line 21, in imports
    import gradio  # noqa: F401
  File "/home/ubuntu/stable-diffusion-webui/stable-diffusion-webui/venv/lib/python3.8/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/home/ubuntu/stable-diffusion-webui/stable-diffusion-webui/venv/lib/python3.8/site-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/home/ubuntu/stable-diffusion-webui/stable-diffusion-webui/venv/lib/python3.8/site-packages/gradio/components/annotated_image.py", line 12, in <module>
    from gradio import utils
  File "/home/ubuntu/stable-diffusion-webui/stable-diffusion-webui/venv/lib/python3.8/site-packages/gradio/utils.py", line 353, in <module>
    class AsyncRequest:
  File "/home/ubuntu/stable-diffusion-webui/stable-diffusion-webui/venv/lib/python3.8/site-packages/gradio/utils.py", line 372, in AsyncRequest
    client = httpx.AsyncClient()
  File "/home/ubuntu/stable-diffusion-webui/stable-diffusion-webui/venv/lib/python3.8/site-packages/httpx/_client.py", line 1397, in __init__
    self._transport = self._init_transport(
  File "/home/ubuntu/stable-diffusion-webui/stable-diffusion-webui/venv/lib/python3.8/site-packages/httpx/_client.py", line 1445, in _init_transport
    return AsyncHTTPTransport(
  File "/home/ubuntu/stable-diffusion-webui/stable-diffusion-webui/venv/lib/python3.8/site-packages/httpx/_transports/default.py", line 275, in __init__
    self._pool = httpcore.AsyncConnectionPool(
TypeError: __init__() got an unexpected keyword argument 'socket_options'
```

Thoughts?

### Reproduction Steps

Just run the ec2 [cloud formation script](https://github.com/awslabs/stable-diffusion-aws-extension/blob/main/workshop/ec2.yaml)

### Possible Solution

I thought it could be a change in the original repo, but the code checks for commit version, so unclear.

### Solution Version

SO8032

### AWS Region. e.g., us-east-1

us-east-1

**Comment by alvindaiyan** [comment]
Issue has been fix in latest pr: https://github.com/awslabs/stable-diffusion-aws-extension/pull/190

**Comment by stenio123** [comment]
Thanks for the quick response! Will check.

BTW I was able to fix it by downgrading the httpx version:
```
cd /home/ubuntu/stable-diffusion-webui
source venv/bin/activate
pip install httpx==0.24.1
/home/ubuntu/stable-diffusion-webui/webui.sh --enable-insecure-extension-access --skip-torch-cuda-test --no-half --listen
```

Looks like they added the socket_options [this Monday](https://github.com/encode/httpx/blob/master/CHANGELOG.md) :-)

**Comment by stenio123** [comment]
Just tested the latest main and it works without the manual fix. Thanks!
